// Cargar los datos de Proveedores
export const CARGAR_PROVEEDORES = 'CARGAR_PROVEEDORES';
export const CARGAR_PROVEEDORES_EXITO = 'CARGAR_PROVEEDORES_EXITO';
export const CARGAR_PROVEEDORES_ERROR = 'CARGAR_PROVEEDORES_ERROR';
//Cargar los datos de la venta
export const CARGAR_VENTAS = 'CARGAR_VENTAS';
export const CARGAR_VENTAS_EXITO = 'CARGAR_VENTAS_EXITO';
export const CARGAR_VENTAS_ERROR = 'CARGAR_VENTAS_ERROR';
// Registrar a los proveedores 
export const REGISTRAR_PROVEEDOR = 'REGISTRAR_PROVEEDORES';
export const REGISTRAR_PROVEEDOR_EXITO = 'REGISTRAR_PROVEEDOR_EXITO';
export const REGISTRAR_PROVEEDOR_ERROR = 'REGISTRAR_PROVEEDOR_ERROR';

// Registrar a los clientes
export const REGISTRAR_CLIENTE = 'REGISTRAR_CLIENTES';
export const REGISTRAR_CLIENTE_EXITO = 'REGISTRAR_CLIENTE_EXITO';
export const REGISTRAR_CLIENTE_ERROR = 'REGISTRAR_CLIENTE_ERROR';

// Editar Perfil Proveedor
export const EDITAR_PROVEEDOR = 'EDITAR_PROVEEDOR';
export const EDITAR_PROVEEDOR_EXITO = 'EDITAR_PROVEEDOR_EXITO';
export const EDITAR_PROVEEDOR_ERROR = 'EDITAR_PROVEEDOR_ERROR';

//Cargar la informacion de la venta(factura)
export const INFORMACION_VENTA = 'INFORMACION_VENTA';
export const INFORMACION_VENTA_EXITO = 'INFORMACION_VENTA_EXITO';
export const INFORMACION_VENTA_ERROR = 'INFORMACION_VENTA_ERROR';
// Cargar la informacion de cada Proveedor
export const INFORMACION_PROVEEDOR = 'INFORMACION_PROVEEDOR';
export const INFORMACION_PROVEEDOR_EXITO = 'INFORMACION_PROVEEDOR_EXITO';
export const INFORMACION_PROVEEDOR_ERROR = 'INFORMACION_PROVEEDOR_ERROR';

//cargar los datos de las publicaciones
export const CARGAR_PUBLICACIONES = 'CARGAR_PUBLICACIONES';
export const CARGAR_PUBLICACIONES_EXITO = 'CARGAR_PUBLICACIONES_EXITO';
export const CARGAR_PUBLICACIONES_ERROR = 'CARGAR_PUBLICACIONES_ERROR';

//Publicaciones por proveedor
export const PUBLICACIONES_PROVEEDOR = "PUBLICACIONES_PROVEEDOR";
export const PUBLICACIONES_PROVEEDOR_EXITO = "PUBLICACIONES_PROVEEDOR_EXITO";
export const PUBLICACIONES_PROVEEDOR_ERROR = "PUBLICACIONES_PROVEEDOR_ERROR";

// Realizar una publicacion
export const CREAR_PUBLICACION = 'CREAR_PUBLICACION';
export const CREAR_PUBLICACION_EXITO = 'CREAR_PUBLICACION_EXITO';
export const CREAR_PUBLICACION_ERROR = 'CREAR_PUBLICACION_ERROR';
export const PORCENTAJE_CARGAR = 'PORCENTAJE_CARGAR';

// Editar Publicacion
export const EDITAR_PUBLICACION = 'EDITAR_PUBLICACION';
export const EDITAR_PUBLICACION_EXITO = 'EDITAR_PUBLICACION_EXITO';
export const EDITAR_PUBLICACION_ERROR = 'EDITAR_PUBLICACION_ERROR';

// Eliminar Publicacion
export const ELIMINAR_PUBLICACION = 'ELIMINAR_PUBLICACION';
export const ELIMINAR_PUBLICACION_EXITO = 'ELIMINAR_PUBLICACION_EXITO';
export const ELIMINAR_PUBLICACION_ERROR = 'ELIMINAR_PUBLICACION_ERROR';

// Cargar Comentarios
export const CARGAR_COMENTARIOS = 'CARGAR_COMENTARIOS';
export const CARGAR_COMENTARIOS_EXITO = 'CARGAR_COMENTARIOS_EXITO';
export const CARGAR_COMENTARIOS_ERROR = 'CARGAR_COMENTARIOS_ERROR';

// Crear Comentarios
export const CREAR_COMENTARIOS = 'CREAR_COMENTARIOS';
export const CREAR_COMENTARIOS_EXITO = 'CREAR_COMENTARIOS_EXITO';
export const CREAR_COMENTARIOS_ERROR = 'CREAR_COMENTARIOS_ERROR';

// Realizar la autenticacion de los usuarios
export const AUTENTICAR_USUARIO = 'AUTENTICAR_USUARIO';
export const AUTENTICAR_USUARIO_EXITO = 'AUTENTICAR_USUARIO_EXITO';
export const AUTENTICAR_USUARIO_ERROR = 'AUTENTICAR_USUARIO_ERROR';

// Alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

//Autenticado 
export const CARGAR_DATOS_USUARIO_AUTENTICADO_EXITO = 'CARGAR_DATOS_USUARIO_AUTENTICADO_EXITO';
export const CARGAR_DATOS_USUARIO_AUTENTICADO_ERROR = 'CARGAR_DATOS_USUARIO_AUTENTICADO_ERROR';

// Validar Token
export const VALIDAR_TOKEN_STORAGE = 'VALIDAR_TOKEN_STORAGE';

//Graficos
export const CARGAR_DATOS = 'CARGAR_DATOS';
export const CARGAR_DATOS_EXITO = "CARGAR_DATOS_EXITO";
export const CARGAR_DATOS_ERROR = "CARGAR_DATOS_ERROR";

// Cargar Productos
export const CARGAR_PRODUCTOS = 'CARGAR_PRODUCTOS';
export const CARGAR_PRODUCTOS_EXITO = 'CARGAR_PRODUCTOS_EXITO';
export const CARGAR_PRODUCTOS_ERROR = 'CARGAR_PRODUCTOS_ERROR';

// Crear Productos
export const CREAR_PRODUCTO = 'CREAR_PRODUCTO';
export const CREAR_PRODUCTO_EXITO = 'CREAR_PRODUCTO_EXITO';
export const CREAR_PRODUCTO_ERROR = 'CREAR_PRODUCTO_ERROR';

// Editar Producto
export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO';
export const EDITAR_PRODUCTO_EXITO = 'EDITAR_PRODUCTO_EXITO';
export const EDITAR_PRODUCTO_ERROR = 'EDITAR_PRODUCTO_ERROR';

// Eliminar Producto
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const ELIMINAR_PRODUCTO_EXITO = 'ELIMINAR_PRODUCTO_EXITO';
export const ELIMINAR_PRODUCTO_ERROR = 'ELIMINAR_PRODUCTO_ERROR';

// Filtrar el Productos por categoria
export const FILTRAR_PRODUCTOS = 'FILTRAR_PRODUCTOS';
export const FILTRAR_PRODUCTOS_EXITO = 'FILTRAR_PRODUCTOS_EXITO';
export const FILTRAR_PRODUCTOS_ERROR = 'FILTRAR_PRODUCTOS_ERROR';

// Filtrar de manera ascendentes los productos
export const FILTRAR_PRODUCTOS_ASCENDENTES = 'FILTRAR_PRODUCTOS_ASCENDENTES';
export const FILTRAR_PRODUCTOS_ASCENDENTES_EXITO = 'FILTRAR_PRODUCTOS_ASCENDENTES_EXITO';
export const FILTRAR_PRODUCTOS_ASCENDENTES_ERROR = 'FILTRAR_PRODUCTOS_ASCENDENTES_ERROR';

// Filtrar de manera descendentes los productos
export const FILTRAR_PRODUCTOS_DESCENDENTES = 'FILTRAR_PRODUCTOS_DESCENDENTES';
export const FILTRAR_PRODUCTOS_DESCENDENTES_EXITO = 'FILTRAR_PRODUCTOS_DESCENDENTES_EXITO';
export const FILTRAR_PRODUCTOS_DESCENDENTES_ERROR = 'FILTRAR_PRODUCTOS_DESCENDENTES_ERROR';

// Filtrar productos por proveedor
export const FILTRAR_PRODUCTOS_PROVEEDOR = 'FILTRAR_PRODUCTOS_PROVEEDOR';
export const FILTRAR_PRODUCTOS_PROVEEDOR_EXITO = 'FILTRAR_PRODUCTOS_PROVEEDOR_EXITO';
export const FILTRAR_PRODUCTOS_PROVEEDOR_ERROR = 'FILTRAR_PRODUCTOS_PROVEEDOR_ERROR';

// Buscador de productos
export const BUSCAR_PRODUCTO = 'BUSCAR_PRODUCTO';
export const BUSCAR_PRODUCTO_EXITO = 'BUSCAR_PRODUCTO_EXITO';
export const BUSCAR_PRODUCTO_ERROR = 'BUSCAR_PRODUCTO_ERROR';

// Cargar Categorias
export const CARGAR_CATEGORIAS = 'CARGAR_CATEGORIAS';
export const CARGAR_CATEGORIAS_EXITO = 'CARGAR_CATEGORIAS_EXITO';
export const CARGAR_CATEGORIAS_ERROR = 'CARGAR_CATEGORIAS_ERROR';

// Filtrar Productos del proveedor por categorias
export const FILTRAR_PRODUCTO_PROVEEDOR_CATEGORIA = 'FILTRAR_PRODUCTO_PROVEEDOR_CATEGORIA'
export const FILTRAR_PRODUCTO_PROVEEDOR_CATEGORIA_EXITO = 'FILTRAR_PRODUCTO_PROVEEDOR_CATEGORIA_EXITO'
export const FILTRAR_PRODUCTO_PROVEEDOR_CATEGORIA_ERROR = 'FILTRAR_PRODUCTO_PROVEEDOR_CATEGORIA_ERROR'

//Calcular Total
export const CALCULAR_TOTAL = 'CALCULAR_TOTAL'
export const CALCULAR_TOTAL_EXITO = 'CALCULAR_TOTAL_EXITO'

// Realizar Pago 
export const REALIZAR_PAGO = 'REALIZAR_PAGO';
export const REALIZAR_PAGO_EXITO = 'REALIZAR_PAGO_EXITO';
export const REALIZAR_PAGO_ERROR = 'REALIZAR_PAGO_ERROR';

